# Generated by Django 6.1.1 on 2026-09-17 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='booking_interval_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='salon',
            name='buffer_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salon',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='salon',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='salon',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
